name: TownyCooldown
version: '${project.version}'
main: me.stephenminer.townycooldown.TownyCooldown
api-version: '1.20'
commands:
  townCooldownReload:
    permission: "tc.commands.reload"
  townSetCooldown:
    permission: "tc.commands.settime"
